on:
  push:
    branches:
      - main
      - alpha
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        swift: ^5.9
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: mxcl/xcodebuild@v1
        with:
          swift: ${{ matrix.swift }}
          platform: ${{ matrix.platform }}
          action: test
          scheme: tkey_pkg
          code-coverage: true
          upload-logs: always