name: Enforce PR Source Branch

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          if ["${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "alpha" ]; then
            echo "Only pull requests from the alpha branch are allowed to main."
            exit 1
          fi